### ISSUE TITLE
Bookbag URL replacement sometimes not working

### ISSUE THREAD

**Issue by nikolaus-lemberski** [sa-mw-dach/microservice-introduction-content#1]
For example 

user6:
Open OpenShift GitOps:
https://argocd-server-user6-gitops.apps.cluster-cs4tm.cs4tm.sandbox1125.opentlc.com/

user7:
Open OpenShift GitOps:
https://argocd-server-user7-gitops/.

**Comment by nikolaus-lemberski** [comment]
maybe because of multi instance deployment?

**Comment by rbo** [comment]
I deployed two instances, sadly I can only deploy serial, not parallel. I cannot reproduce the problem. 

If I remember correctly, we had the problem on container days too. We restarted the pods and it works pretty well.
